sudo: false
cache: bundler
language: ruby
before_script:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc' # skip installing docs for gems
before_install:
  - gem install bundler -v ">= 1.8.0" # Minimum version of bundler required
bundler_args: --without development
script: 'bundle exec rake test'
services:
  - mongodb
  - redis-server
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-19mode
env:
  - DB=mongodb
  - DB=redis
  - DB=active_record
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails42_protected_attributes.gemfile
